### ISSUE TITLE
Necessário aumentar o limite dos campos nas classes de tabelas

### ISSUE THREAD

**Issue by renanbenedicto** [cauethenorio/edne-correios-loader#1]
Na classe `tabelas.py` é necessário aumentar os campos de abreviatura e logradouro para `sa.Unicode(xx)` onde xx deve ser >= 200.

**Comment by cauethenorio** [comment]
@renanbenedicto as definições dos campos de cada tabela foram reescritas e agora seguem os tamanhos indicados pela documentação do e-DNE. Estou fechando esse issue, fique a vontade para reabrir se ainda tiver problemas.
