### ISSUE TITLE
Incompatibilidade do schema atual de tabelas com SQL SERVER

### ISSUE THREAD

**Issue by LTeCosta** [cauethenorio/edne-correios-loader#3]
Olá!

Estou utilizando o script com SQL server e tive um problema de incompatibilidade por referência circular no campo loc_localidade.loc_nu_sub.

Alterando o ondelete para "NO ACTION" resolveu o problema e o script funcionou corretamente. Segue abaixo definição da tabela alterada.

```
log_localidade = Table(
    "log_localidade",
    metadata,
    Column(
        "loc_nu",
        Integer,
        primary_key=True,
        unique=True,
        comment="Chave da localidade",
        nullable=False,
    ),
    Column(
        "ufe_sg",
        String(2),
        primary_key=True,
        comment="Sigla da UF",
        nullable=False,
    ),
    Column("loc_no", String(72), comment="Nome da localidade", nullable=False),
    # CEP da localidade(para localidade não codificada, ou seja, loc_in_sit = 0)
    Column("cep", String(8), index=True, comment="CEP da localidade"),
    Column(
        "loc_in_sit",
        Enum(
            SituacaoLocalidadeEnum,
            values_callable=lambda x: [e.value for e in x],
        ),
        comment="Situação da localidade",
        nullable=False,
    ),
    Column(
        "loc_in_tipo_loc",
        Enum(TipoLocalidadeEnum, values_callable=lambda x: [e.value for e in x]),
        comment="Tipo de localidade",
        nullable=False,
    ),
    Column(
        "loc_nu_sub",
        ForeignKey("log_localidade.loc_nu", ondelete="NO ACTION"),
        index=True,
        comment="Chave da localidade de subordinação",
    ),
    Column("loc_no_abrev", String(36), comment="Abreviatura do nome da localidade"),
    Column("mun_nu", Integer, comment="Código do município IBGE"),
)
```

**Comment by cauethenorio** [comment]
Oi, Lucas!

Obrigado por relatar o problema, acabei de publicar uma nova versão utilizando sua sugestão da solução para o problema, espero que agora você consiga rodar o script sem problemas.

Estou fechando essa issue mas pode reabrir ou abrir outra se tiver mais problemas.

**Comment by eduzue** [comment]
Olá.
Quanto ao comando ON DELETE=NO ACTION, no Oracle não funciona. Ou seja, não possui essa cláusula "NO ACTION", e mostra o erro:

"name": "DatabaseError",
	"message": "(oracledb.exceptions.DatabaseError) ORA-00905: missing keyword\nHelp: https://docs.oracle.com/error-help/db/ora-00905/\n[SQL: \nCREATE TABLE log_localidade (\n\tloc_nu INTEGER NOT NULL, \n\tufe_sg VARCHAR2(2 CHAR) NOT NULL, \n\tloc_no VARCHAR2(72 CHAR) NOT NULL, \n\tcep VARCHAR2(8 CHAR), \n\tloc_in_sit VARCHAR(1 CHAR) NOT NULL, \n\tloc_in_tipo_loc VARCHAR(1 CHAR) NOT NULL, \n\tloc_nu_sub INTEGER, \n\tloc_no_abrev VARCHAR2(36 CHAR), \n\tmun_nu INTEGER, \n\tPRIMARY KEY (loc_nu, ufe_sg), \n\tUNIQUE (loc_nu), \n\tFOREIGN KEY(loc_nu_sub) REFERENCES log_localidade (loc_nu) ON DELETE NO ACTION\n)
